### PR TITLE
import threading instead of thread

### PR DESCRIPTION
**Pull request by ZER-0-NE**
Import threading instead of thread in python3 to rectify the "import thread error".

### CODE REVIEW

**Comment by EvilPort2** [comment]
The import thread error can be easily removed if you follow this link  https://stackoverflow.com/questions/36809788/importerror-no-module-named-thread. 
import threading won't resolve the error.

**Comment by ZER-0-NE** [comment]
It did work for me actually.

**Comment by EvilPort2** [comment]
let me check

**Comment by EvilPort2** [comment]
Simply "import threading" does not work in Python 3.x. I do not know for Python 2.x. If you do "import threading" then you need to change every occurrence of "start_new_thread" to "threading._start_new_thread".

**Pull request closed without merging**
